### ISSUE TITLE
rescue mode segfaults

### ISSUE THREAD

**Issue by xloem** [recordmydesktop/recordmydesktop#2]
I'm getting different segfaults when I pass --rescue .

**Comment by xloem** [comment]
2101b1f76e5e7eab4b4ea632db226fb76d99eeda introduced a segfault during --rescue for me
Here's a backtrace taken from building that crash-introducing commit.  Current tip also sees this behavior if the other problem I mention is commented out:
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffef76f700 (LWP 5857)]
0x00007ffff5207618 in __memcpy_ssse3 () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install alsa-lib-1.1.8-1.el7.x86_64 glibc-2.17-317.el7.x86_64 jack-audio-connection-kit-1.9.9.5-6.el7.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.7-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXdamage-1.1.4-4.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 libtheora-1.1.1-8.el7.x86_64 libuuid-2.23.2-61.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 libxcb-1.13-1.el7.x86_64 opus-1.0.2-6.el7.x86_64 popt-1.13-16.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x00007ffff5207618 in __memcpy_ssse3 () from /lib64/libc.so.6
#1  0x000000000040c5cb in rmdLoadBlock (dest=0x7ffff3d26010 "", source=0x7fffeed78010 "", blockno=8040, width=1920, height=1072, blockwidth=16) at rmd_load_cache.c:82
#2  0x000000000040cf5c in rmdLoadCache (pdata=0x7fffffffc870) at rmd_load_cache.c:262
#3  0x00007ffff74a2ea5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffff51b796d in clone () from /lib64/libc.so.6
```

5ce6553ccf5502fc71d11d654c76bd1714cd36dd introduced a floating point exception during --rescue for me, the progress meter divides by zero when accessing the total frames.  

Here's a backtrace from building 5ce6553.  This behavior is also seen in the current tip:
```
Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffef76f700 (LWP 6230)]
0x000000000040cdd0 in rmdLoadCache (pdata=0x7fffffffc880) at rmd_load_cache.c:240
240                                     fprintf(stdout, "\r[%d%%] ",
Missing separate debuginfos, use: debuginfo-install alsa-lib-1.1.8-1.el7.x86_64 glibc-2.17-317.el7.x86_64 jack-audio-connection-kit-1.9.9.5-6.el7.x86_64 libICE-1.0.9-9.el7.x86_64 libSM-1.2.2-2.el7.x86_64 libX11-1.6.7-2.el7.x86_64 libXau-1.0.8-2.1.el7.x86_64 libXdamage-1.1.4-4.1.el7.x86_64 libXext-1.3.3-3.el7.x86_64 libXfixes-5.0.3-1.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libogg-1.3.0-7.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 libtheora-1.1.1-8.el7.x86_64 libuuid-2.23.2-61.el7.x86_64 libvorbis-1.3.3-8.el7.1.x86_64 libxcb-1.13-1.el7.x86_64 opus-1.0.2-6.el7.x86_64 popt-1.13-16.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  0x000000000040cdd0 in rmdLoadCache (pdata=0x7fffffffc880) at rmd_load_cache.c:240
#1  0x00007ffff74a2ea5 in start_thread () from /lib64/libpthread.so.0
#2  0x00007ffff51b796d in clone () from /lib64/libc.so.6
```

**Comment by vcaputo** [comment]
Hmm, I haven't used --rescue so I'm unsurprised to hear it's bugged.

The statistics and likely progress stuff in general need some attention, my focus thus far has been on more core functionalities working properly.

If you're up for preparing a PR to address this I'll be happy to review it, otherwise eventually I'll get around to digging into this myself.

**Comment by vcaputo** [comment]
@xloem could you try repro the segfault with the changes in master?

I'm unable to reproduce the segfault on --rescue here, but there were some uninitialized structs in that mode which I've fixed.

**Comment by xloem** [comment]
Yeah, no more segfault =)

I'm not using this software right now anymore myself, but a next issue would be that the process deletes its intermediate data if it is terminated before encoding completes.
